name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-e2e:
    name: E2E test
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - run: go run . -uroot -hlocalhost -P3306 --timeout=60
