name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-e2e:
    name: E2E test
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8
        ports:
          - 3306/tcp
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          cache: false
      - name: Ping MySQL
        run: go run . -uroot -hlocalhost -P${{ job.services.db.ports[3306] }} --timeout=60
